### PR TITLE
Fix errors in documentation (code examples).

### PR DESCRIPTION
**Pull request by laradevitt**
Boy, I hope this works or I will be embarrassed. 😳 😅

### CODE REVIEW

**Comment by laradevitt** [comment]
@horacioh - any insights here?

**Comment by horacioh** [comment]
so sorry i did not see this!

let me check it as soon as I get home!

**Comment by horacioh** [comment]
@all-contributors please add @laradevitt for documentation

**Comment by horacioh** [comment]
@all-contributors please add @horacioh for documentation, code, design, example, video, tutorial, review

**Pull request merged**
